#!/bin/bash

#program to output system information page

TITLE="System Information Page for $HOSTNAME"
CURRENT_TIME=$(date +"%x %r %Z")
TIMESTAMP="Generated $CURRENT_TIME, by $USER"

#shell function definitions--must come befor call

# reports time since last poweron
function report_uptime {
	cat <<- _EOF_
		<h2>System Uptime</h2>
		<pre>$(uptime)</pre>
		_EOF_
	return
}

#reports total disk space. the df command is used with human readable option -h
function report_disk_space {
	cat <<- _EOF_
		<h2>Disk Space Utilization</h2>
		<pre>$(df -h)</pre>
		_EOF_
	return
}

# reports amount of space used by each user
function report_home_space {
	if [[$(id -u) == 0]]; then
			cat <<- _EOF_
				<h2>Home Space Utilization (All Users)</h2>
				<pre>$(du -sh /home/*)</pre>
			_EOF_
	else
		cat <<- _EOF_
			<h2>Home Space Utilization ($USER)</h2>
			<pre>$(du -sh $HOME)</pre>
			_EOF_
	fi
	
	return 
}

# a 'here' document. embeds a body of text and feeds it 
# into stdin of cat
# <<- ignores leading tab characters, good for readability
cat <<- _EOF_
 <html>
	<head>
	 	<title>$TITLE</title>
	</head>
 	
	<body>
		<h1>$TITLE</h1>
		<p>$TIMESTAMP</p>
		$(report_uptime)
		$(report_disk_space)
		$(report_home_space)
	</body>
</html>
_EOF_


